rasterizer:
	g++ -std=c++17 -o rasterizer tinymath.cpp hw2_file_ops.cpp rasterizer.cpp -g

debug:
	g++ -std=c++17 -Wall -Wextra -o rasterizer tinymath.cpp hw2_file_ops.cpp rasterizer.cpp -g

clean:
	rm -rf *.ppm *.png ./rasterizer
